name: Test and Build Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '21.x']
        mongodb-version: ['4.2', '4.4', '5.0', '6.0', '7.0']

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Make Env File
        uses: SpicyPizza/create-envfile@v2.0
        with:
          # Database variables
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          # Server  variables
          envkey_SERVER_PORT: ${{ secrets.SERVER_PORT }}
          envkey_SERVER_URL: ${{ secrets.SERVER_URL }}
          envkey_SERVER_SECRET_KEY: ${{ secrets.SERVER_SECRET_KEY }}
          # Mail service variables
          envkey_MAIL_NAME: ${{ secrets.MAIL_NAME }}
          envkey_MAIL_EMAIL: ${{ secrets.MAIL_EMAIL }}
          envkey_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: ${{ secrets.DB_USER }}
          mongodb-password: ${{ secrets.DB_PASSWORD }}
          mongodb-db: pnu

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
